
export const actions_types = {
    // Auth
    USER_LOADING:'USER_LOADING',
    USER_LOADED:'USER_LOADED',
    AUTH_ERROR :'AUTH_ERROR',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAIL:'LOGIN_FAIL',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    GET_ERRORS:'GET_ERRORS',
    CREATE_MESSAGE:'CREATE_MESSAGE',
    REGISTRATION_SUCCESS:'REGISTRATION_SUCCESS',
    REGISTRATION_FAIL:'REGISTRATION_FAIL',
    USER_VERIFICATION:'USER_VERIFICATION',
    ACTION_FAIL:'ACTION_FAIL',

    // Users
    USER_ROLES:'USER_ROLES',
    GETTING_USER:'GETTING_USER',
    ADDING_USER:'ADDING_USER',
    UPDATING_USER:'UPDATING_USER',
    DELETING_USER:'DELETING_USER',
    ADD_USER:'ADD_USER',
    GET_USER:'GET_USER',
    UPDATE_USER:'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    SELECTED_USER:'SELECTED_USER',

    // Vendors
    GETTING_VENDOR:'GETTING_VENDOR',
    ADDING_VENDOR:'ADDING_VENDOR',
    UPDATING_VENDOR:'UPDATING_VENDOR',
    DELETING_VENDOR:'DELETING_VENDOR',
    ADD_VENDOR:'ADD_VENDOR',
    GET_VENDOR:'GET_VENDOR',
    UPDATE_VENDOR:'UPDATE_VENDOR',
    DELETE_VENDOR: 'DELETE_VENDOR',
    SELECTED_VENDOR:'SELECTED_VENDOR',

    // Vendors
    GETTING_SME:'GETTING_SME',
    ADDING_SME:'ADDING_SME',
    UPDATING_SME:'UPDATING_SME',
    DELETING_SME:'DELETING_SME',
    ADD_SME:'ADD_SME',
    GET_SME:'GET_SME',
    UPDATE_SME:'UPDATE_SME',
    DELETE_SME: 'DELETE_SME',
    SELECTED_SME:'SELECTED_SME',
}

