
export const actions_types = {
    // Auth
    USER_LOADING:'USER_LOADING',
    USER_LOADED:'USER_LOADED',
    AUTH_ERROR :'AUTH_ERROR',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAIL:'LOGIN_FAIL',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    GET_ERRORS:'GET_ERRORS',
    CREATE_MESSAGE:'CREATE_MESSAGE',
    REGISTRATION_SUCCESS:'REGISTRATION_SUCCESS',
    REGISTRATION_FAIL:'REGISTRATION_FAIL',
    USER_VERIFICATION:'USER_VERIFICATION',
    ACTION_FAIL:'ACTION_FAIL',

    // Users
    USER_ROLES:'USER_ROLES',
    GETTING_USER:'GETTING_USER',
    ADDING_USER:'ADDING_USER',
    UPDATING_USER:'UPDATING_USER',
    DELETING_USER:'DELETING_USER',
    ADD_USER:'ADD_USER',
    GET_USER:'GET_USER',
    UPDATE_USER:'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    SELECTED_USER:'SELECTED_USER',
    GET_TRAINERS:'GET_TRAINERS',

    // Vendors
    GETTING_VENDOR:'GETTING_VENDOR',
    ADDING_VENDOR:'ADDING_VENDOR',
    UPDATING_VENDOR:'UPDATING_VENDOR',
    DELETING_VENDOR:'DELETING_VENDOR',
    ADD_VENDOR:'ADD_VENDOR',
    GET_VENDOR:'GET_VENDOR',
    UPDATE_VENDOR:'UPDATE_VENDOR',
    DELETE_VENDOR: 'DELETE_VENDOR',
    SELECTED_VENDOR:'SELECTED_VENDOR',

    // Vendors
    GETTING_SME:'GETTING_SME',
    ADDING_SME:'ADDING_SME',
    UPDATING_SME:'UPDATING_SME',
    DELETING_SME:'DELETING_SME',
    ADD_SME:'ADD_SME',
    GET_SME:'GET_SME',
    UPDATE_SME:'UPDATE_SME',
    DELETE_SME: 'DELETE_SME',

    // COnsultant
    GETTING_CONSULTANT:'GETTING_CONSULTANT',
    ADDING_CONSULTANT:'ADDING_CONSULTANT',
    UPDATING_CONSULTANT:'UPDATING_CONSULTANT',
    DELETING_CONSULTANT:'DELETING_CONSULTANT',
    ADD_CONSULTANT:'ADD_CONSULTANT',
    GET_CONSULTANT:'GET_CONSULTANT',
    UPDATE_CONSULTANT:'UPDATE_CONSULTANT',
    DELETE_CONSULTANT: 'DELETE_CONSULTANT',

    // Training category
    GETTING_TRAINING_CATEGORY:'GETTING_TRAINING_CATEGORY',
    ADDING_TRAINING_CATEGORY:'ADDING_TRAINING_CATEGORY',
    UPDATING_TRAINING_CATEGORY:'UPDATING_TRAINING_CATEGORY',
    DELETING_TRAINING_CATEGORY:'DELETING_TRAINING_CATEGORY',
    ADD_TRAINING_CATEGORY:'ADD_TRAINING_CATEGORY',
    GET_TRAINING_CATEGORY:'GET_TRAINING_CATEGORY',
    UPDATE_TRAINING_CATEGORY:'UPDATE_TRAINING_CATEGORY',
    DELETE_TRAINING_CATEGORY: 'DELETE_TRAINING_CATEGORY',

    // Training
    GETTING_TRAINING:'GETTING_TRAINING',
    ADDING_TRAINING:'ADDING_TRAINING',
    UPDATING_TRAINING:'UPDATING_TRAINING',
    DELETING_TRAINING:'DELETING_TRAINING',
    ADD_TRAINING:'ADD_TRAINING',
    GET_TRAINING:'GET_TRAINING',
    UPDATE_TRAINING:'UPDATE_TRAINING',
    DELETE_TRAINING: 'DELETE_TRAINING',
    GET_SINGLE_TRAINING: 'GET_SINGLE_TRAINING',

    // Products
    GETTING_PRODUCT:'GETTING_PRODUCT',
    ADDING_PRODUCT:'ADDING_PRODUCT',
    UPDATING_PRODUCT:'UPDATING_PRODUCT',
    DELETING_PRODUCT:'DELETING_PRODUCT',
    ADD_PRODUCT:'ADD_PRODUCT',
    GET_PRODUCT:'GET_PRODUCT',
    UPDATE_PRODUCT:'UPDATE_PRODUCT',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    GET_SINGLE_PRODUCT: 'GET_SINGLE_PRODUCT',

    // Products category
    GETTING_PRODUCT_CATEGORY:'GETTING_PRODUCT_CATEGORY',
    ADDING_PRODUCT_CATEGORY:'ADDING_PRODUCT_CATEGORY',
    UPDATING_PRODUCT_CATEGORY:'UPDATING_PRODUCT_CATEGORY',
    DELETING_PRODUCT_CATEGORY:'DELETING_PRODUCT_CATEGORY',
    ADD_PRODUCT_CATEGORY:'ADD_PRODUCT_CATEGORY',
    GET_PRODUCT_CATEGORY:'GET_PRODUCT_CATEGORY',
    UPDATE_PRODUCT_CATEGORY:'UPDATE_PRODUCT_CATEGORY',
    DELETE_PRODUCT_CATEGORY: 'DELETE_PRODUCT_CATEGORY',
    GET_SINGLE_PRODUCT_CATEGORY: 'GET_SINGLE_PRODUCT_CATEGORY',

    // research category
    GETTING_RESEARCH_CATEGORY:'GETTING_RESEARCH_CATEGORY',
    ADDING_RESEARCH_CATEGORY:'ADDING_RESEARCH_CATEGORY',
    UPDATING_RESEARCH_CATEGORY:'UPDATING_RESEARCH_CATEGORY',
    DELETING_RESEARCH_CATEGORY:'DELETING_RESEARCH_CATEGORY',
    ADD_RESEARCH_CATEGORY:'ADD_RESEARCH_CATEGORY',
    GET_RESEARCH_CATEGORY:'GET_RESEARCH_CATEGORY',
    UPDATE_RESEARCH_CATEGORY:'UPDATE_RESEARCH_CATEGORY',
    DELETE_RESEARCH_CATEGORY: 'DELETE_RESEARCH_CATEGORY',
    GET_SINGLE_RESEARCH_CATEGORY: 'GET_SINGLE_RESEARCH_CATEGORY',

    // Research
    GETTING_RESEARCH:'GETTING_RESEARCH',
    ADDING_RESEARCH:'ADDING_RESEARCH',
    UPDATING_RESEARCH:'UPDATING_RESEARCH',
    DELETING_RESEARCH:'DELETING_RESEARCH',
    ADD_RESEARCH:'ADD_RESEARCH',
    GET_RESEARCH:'GET_RESEARCH',
    UPDATE_RESEARCH:'UPDATE_RESEARCH',
    DELETE_RESEARCH: 'DELETE_RESEARCH',
    GET_SINGLE_RESEARCH: 'GET_SINGLE_RESEARCH',
    SELECTED_RESEARCH_IMAGE:'SELECTED_RESEARCH_IMAGE',

    // Appointments
    GETTING_APPOINTMENT:'GETTING_APPOINTMENT',
    ADDING_APPOINTMENT:'ADDING_APPOINTMENT',
    UPDATING_APPOINTMENT:'UPDATING_APPOINTMENT',
    DELETING_APPOINTMENT:'DELETING_APPOINTMENT',
    ADD_APPOINTMENT:'ADD_APPOINTMENT',
    GET_APPOINTMENT:'GET_APPOINTMENT',
    UPDATE_APPOINTMENT:'UPDATE_APPOINTMENT',
    DELETE_APPOINTMENT: 'DELETE_APPOINTMENT',
    USER_APPOINTMENT:'USER_APPOINTMENT',
    CONSULTANT_APPOINTMENT:'CONSULTANT_APPOINTMENT',

    // COntact us
    ADDING_CONTACT:'ADDING_CONTACT',
    ADD_CONTACT:'ADD_CONTACT',
}

