
export const actions_types = {
    USER_LOADING:'USER_LOADING',
    USER_LOADED:'USER_LOADED',
    AUTH_ERROR :'AUTH_ERROR',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAIL:'LOGIN_FAIL',
    LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
    GET_ERRORS:'GET_ERRORS',
    CREATE_MESSAGE:'CREATE_MESSAGE'
}

